name: Caller Workflow

on: workflow_dispatch

jobs:
  call-workflow:
    uses: andaritri/gh-actions/.github/workflows/ci.yml@main
    secrets:
        DEV_PROJECT: ${{ secrets.DEV_PROJECT }}
        STG_PROJECT: ${{ secrets.STG_PROJECT }}
