name: Caller Workflow

on:
  workflow_run:
    workflows: ['Several Enviroments']
    types:
      - completed

jobs:
  call-workflow:
    uses: andaritri/gh-actions/.github/workflows/ci.yml@main
    secrets:
        DEV_PROJECT: ${{ secrets.DEV_PROJECT }}
        STG_PROJECT: ${{ secrets.STG_PROJECT }}
